### ISSUE TITLE
InfinityGrid bugged in img2img mode

### ISSUE THREAD

**Issue by Emasoft** [mcmonkeyprojects/sd-infinity-grid-generator-script#123]
Currently InfinityGrid can only be used in txt2img mode. But I often need to evaluate the impact of some parameters (i.e. denoising) in img2img mode. When I tried to use it in img2img mode it gives the following error: 

```
AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'enable_hr'
```

But it should be theoretically possible to do it in img2img, since the Plot X/Y/Z script works fine in such mode.

**Comment by mcmonkey4eva** [comment]
Bug, not feature request - it's listed under img2img explicitly and is meant to work, that's a bug if it's breaking

**Comment by mcmonkey4eva** [comment]
yep, minor bug introduced by #93 - fixed
